### ISSUE TITLE
Plain ELAS missing

### ISSUE THREAD

**Issue by SagevdBrand** [asreview/asreview-artwork#6]
While searching for a plain version of ELAS (without "ASReview"), it appeared that a simple ELAS as an icon was missing! 🕵️‍♀️ 🔍 
Can this be added to the repo?

**Comment by Rensvandeschoot** [comment]
see https://github.com/asreview/asreview-artwork/blob/master/LogoASReview/PNG/Icon.png

**Comment by SagevdBrand** [comment]
https://github.com/asreview/asreview-artwork/blob/master/LogoASReview/PNG/Icon.png 

Found it! Thanks to @Rensvandeschoot
